version: "3"

services:
  hello-world-app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: hello-world-js-app:1.0
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    command: ["nodemon", "index.js"]
